configs:
- id: f254c84c-b4ff-3bd4-ab0d-26159c476114
  config:
    template: f254c84c-b4ff-3bd4-ab0d-26159c476114.json
    skip: false
    originObjectId: vu9U3hXa3q0AAAABACFidWlsdGluOmFwcC10cmFuc2l0aW9uLmt1YmVybmV0ZXMABnRlbmFudAAGdGVuYW50ACRhYWUyOWZmOC1iOWM3LTNlMWUtODg4Yy1hYWFhYzVmZTZlMmO-71TeFdrerQ
  type:
    settings:
      schema: builtin:app-transition.kubernetes
      schemaVersion: "1.1"
      scope: environment